### PR TITLE
Fparser2

### PR DESCRIPTION
**Pull request by bblay**
This PR replaces the in-house Fortran parser with fparser2.

It's also built upon a few other open PRs, which should probably be merged or closed first.

### CODE REVIEW

**Comment by bblay** [comment]
rebuild

**Comment by bblay** [comment]
Ah, I've used walrus operator for the first time because they are nice and tidy, but that requires Python 3.8. Is it ok to bump setup.py to 3.8? If not, I can just replace the walrus operators instead, no problem.

**Comment by stevewardle** [comment]
> Ah, I've used walrus operator for the first time because they are nice and tidy, but that requires Python 3.8. Is it ok to bump setup.py to 3.8? If not, I can just replace the walrus operators instead, no problem.

I think I'd avoid restricting us to 3.8+ just for this feature

**Comment by bblay** [comment]
I'm going to close this as we're really just working on one big feature branch.

**Pull request closed without merging**
