### PR TITLE
Create artefact store

### LINKED ISSUE #280: Create Standalone ArtefactStore
There is a todo that using `build_config._artefact_store` is not ideal. This tickets introduces an ArtefactStore objects (inhering from Dict, so all functionality remains), and adds a getter to `BuildConfig` to access it. It also contains some code cleanup based on pylint/pycodestyle.

### PR DESCRIPTION
**Pull request by hiker**
Fixes #280. It just adds a tiny new object (based on Dict) for artefact_store and adds a property to access it.

### CODE REVIEW

**Comment by t00sa** [comment]
The unit tests fail with an error in tests/unit_tests/steps/test_link.py.  I suspect this is due to the use of a SimpleNamespace instance with an explicit _artefact_store dictionary.

**Comment by hiker** [comment]
Thanks a lot @t00sa for the (start of a) review, and my apologies for the CI failure. In PSyclone, submitting a PR triggers the CI, and then when a dev is happy, they add the label 'ready for review'. I realised later that a) no CI is triggered automatically, and b) I can't add a label :) I should have added a comment.

I am finishing this PR, but I wonder if it would be possible to get some more access so that I can add labels as required, and maybe trigger the CI (we have some more PRs coming in, one of the first one fixing the test failures we see with PSyclone 2.5). We are doing an internal review first (and I believe we now can run the test suite locally), but getting the ability to trigger the CI here would be really great, just to catch any differences between our local systems and the git CI.

**Comment by t00sa** [comment]
Sorry if I jumped on you PR too soon - we are still sorting out our working practices for github.  I'll talk to the rest of the team about this because it seems sensible to have a way that lets you run the CI tests without immediately having someone pick up your PR for review.

I'll check with one of the project admins to see what we can do about allowing you to run the tests without requiring approval every time.  The github documentation implies that it is only necessary for first time contributors, so it is possible the problem will go away once your PR is on the trunk.

**Comment by hiker** [comment]
Closing this for now, I have a new branch ready at https://github.com/hiker/fab/pull/8

**Pull request closed without merging**
