### PR TITLE
Start design

### PR DESCRIPTION
**Pull request by MatthewHambley**
Started some design documentation with UML diagrams for a graph representation. This is in no way complete work or necessarily representative of any final design.

The files may be converted into graphics using the PlantUML tool.

### CODE REVIEW

**Comment by stevewardle** [comment]
Perhaps we should include the generated graphics alongside?  (or is the plan to put these directly onto the wiki?)

**Comment by MatthewHambley** [comment]
I have a strong aversion to manually generating renders and uploading them to the wiki. And generated anything simply doesn't belong in a VCS repository.

There seems to be a mechanism to have the wiki make use of a render server: https://stackoverflow.com/questions/32203610/how-to-integrate-uml-diagrams-into-gitlab-or-github

**Comment by stevewardle** [comment]
Yeah in hindsight I agree with you.  Are you wanting this merged at this point?

**Comment by MatthewHambley** [comment]
Lets get it on and we can try generating the images later.

**Pull request merged**
