### PR TITLE
Fab deps

### PR DESCRIPTION
**Pull request by bblay**
Tidies up the dependencies between the conda and setup.py:
 - The _setup.py_ `extras` section has packages for general dev.
 - The earliest clang release available at MO, 8.0.1, tested and added to conda env.
   - _python-clang_ not added to _setup.py_ because it seems better to install it alongside the linux _libclang_ package so we can match versions. Might be worth a chat about this.

todo:
 - [x] retest manually before merge

### CODE REVIEW

**Review by GiorgiaLine — COMMENTED** [review]
Looks good, just one question about run-configs.sh; Are the commented out build scripts/flags being left in for development purposes? If so, I'm hsppy to approve this.

**Comment by bblay** [comment]
> Looks good, just one question about run-configs.sh; Are the commented out build scripts/flags being left in for development purposes? If so, I'm hsppy to approve this.

Yes that's right. The whole script has been replaced with a simpler Python version in another PR anyhoo.

**Review by GiorgiaLine — DISMISSED** [review]

**Review by GiorgiaLine — APPROVED** [review]
Conflicts resolved... except I just made new ones.

**Review by GiorgiaLine — APPROVED** [review]
Third time's the charm.

**Pull request merged**
